language: node_js
node_js:
  - "10"
sudo: required
services:
  - docker
before_install:
  - docker run -d -p 7845:7845 --name aergosvr aergo/node:0.8.3 aergosvr --config /aergo/config.toml --testmode
install:
  - npm install
before_script:
  - sleep 5
script:
  - npm test
after_failure:
  - docker logs aergosvr
after_script:
  - docker kill aergosvr