language: go
go:
  - "1.10.x"
before_install:
  - export PATH=./node_modules/.bin:$PATH
  - nvm install 8
  - go get -t github.com/Masterminds/glide
  - AERGO_VERSION=`cat "package.json" | python -c "import sys, json; print json.load(sys.stdin)['aergo']['version']"`
  - go get -d github.com/aergoio/aergo || true
  - cd ${GOPATH}/src/github.com/aergoio/aergo && git checkout ${AERGO_VERSION} && make deps && make aergosvr
  - cd ${TRAVIS_BUILD_DIR}
install:
  - npm install
script:
  - ${GOPATH}/src/github.com/aergoio/aergo/bin/aergosvr >/dev/null 2>&1 &
  - npm test